### ISSUE TITLE
一键部署到 Vercel 时遇到错误

### ISSUE THREAD

**Issue by ghost** [CaoMeiYouRen/screen-cloud-function#2]
Error: No Output Directory named "public" found after the Build completed. You can configure the Output Directory in your Project Settings.

**Comment by CaoMeiYouRen** [comment]
请将 `Output Directory` 设置为 `.`
![image](https://github.com/user-attachments/assets/9b2e245c-4f40-43f7-99aa-9a92816b0e43)

**Comment by CaoMeiYouRen** [comment]
最新版本已修复该问题，设置为 `public` 可避免暴露源文件
